### ISSUE TITLE
Cell / Column misalignment issue when created in CSV

### ISSUE THREAD

**Issue by nickdegiacomo** [MeltanoLabs/target-csv#1]
I have been trying to run a tap-shopify to target-athena pipeline. However, when checking created tables in Athena, some cells are misaligned. The same issue happens in target-csv.

 The data is heavily nested and includes arrays of JSON. e.g., If a customer purchases 1 item vs. five items, then line_items (and other columns) will grow to fit information on each. 

https://github.com/MeltanoLabs/target-athena/issues/27

**Comment by aaronsteers** [comment]
@nickdegiacomo - Resolved in #2
