### ISSUE TITLE
Create the directory automatically if it doesn't exist

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/target-csv#70]
Create the directory automatically if it doesn't exist

**Comment by HyoungSooo** [comment]
hi @visch can i get this issue?

**Comment by visch** [comment]
@HyoungSooo  sure! Be sure to think about nested directories, I think  Python has some nice functions for this! `Path.mkdir` if I remember correctly

**Comment by edgarrmondragon** [comment]
Closed by https://github.com/MeltanoLabs/target-csv/pull/73
